project:
  type: website
  output-dir: docs
website:
  title: "Hongke (Amy) Wu"
  navbar:
    background: dark
    foreground: info
    border: true
    alignment: center
    style: floating
    search: true
    left:
      - href: index.qmd
        text: Profile
      - href: Publications.qmd
        text: Publications
      - href: Post.qmd
        text: Post
  page-footer: "Philippians 4:13 - I can do all things through him who strengthens me."
format:
  html:
    theme: quartz
    fontsize: 1.1em
    mainfont: cursive
    css: styles.css
    toc: true