project:
  type: website
  output-dir: docs
website:
  title: "Hongke (Amy) Wu"
  navbar:
    background: dark
    foreground: info
    border: true
    alignment: center
    style: floating
    search: true
    left:
      - href: index.qmd
        text: Profile
      - href: Publications.qmd
        text: Publications
  page-footer: "Psalm 119:105 Your word is a lamp for my feet, a light on my path."
format:
  html:
    theme: quartz
    fontsize: 1.1em
    mainfont: consolas
    grid: 
      body-width: 1000px
    css: styles.css
    toc: true