project:
  type: website
  output-dir: docs
website:
  title: "Hongke (Amy) Wu"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Profile
      - href: Publications.qmd
        text: Publications
      - href: Post.qmd
        text: Post
format:
  html:
    theme: quartz
    css: styles.css
    toc: true


