---
title: "Publications"
format: html
---


$$\text{In-processed Papers}$$

1. Hongke Wu, Ye Liu, Jingyi Zhang, Bisakha Sen, Jeffrey R. Curtis. Individual and Community-level Determinants of Osteoporosis Treatment Following Fracture Among Medicare Beneficiaries. (Under Review)

2. Ming A Wang, Hongke Wu, Aaron Bonner-Jackson, Yiming Chen, Wen Tang, Hao Feng, Lijun Zhang, Chixiang Chen, James Leverenz, Jagan A Pillai. Distinct Subtypes with Early Behavioral and Cognitive Changes in Neuropathology Confirmed Dementia. (Under Review)


$$\text{2025 Accepted Conference Abstracts}$$

1. Ye Liu, Hongke Wu, Tarun Arora, Jeffrey R Curtis. Association Between Past Osteoporosis Treatment Adherence and Romosozumab Adherence Among Early Adopters: A Trajectory Analysis. (SMDM 2025, Abstract ID: 31891)

2. Hongke Wu, Ye Liu, Tarun Arora, Jeffrey R Curtis. Bayesian Analysis of Factors Associated with Romosozumab Adherence Among Early Adopters in Medicare Beneficiaries. (ISPE 2025, Abstract ID: 2055366)

3. Ye Liu, Hongke Wu, Tarun Arora, Jeffrey R Curtis. Comedication Patterns of Romosozumab Early Adopters Among Medicare Enrollees: An Unsupervised Clustering Approach. (ISPE 2025, Abstract ID: 2054580)

4. Ye Liu, Hongke Wu, Amy Mudano, Omar Safarini, John Eddins, Carlos Cardenas, Leslye Jackson, Jeffrey R Curtis, Steven Rothenberg. Using Abdominal CT-Derived Bone Mineral Density and Psoas Volume for Opportunistic Osteoporosis Screening and Fracture Risk Assessment. (ASBMR 2025 Plenary Poster)


$$\text{Published Papers/Abstracts}$$
1. Wu, Hongke, Ming Wang, and Alicia C. McDonald. "Association between dietary intake and urinary concentrations of caffeine and caffeine metabolites and elevated serum prostate-specific antigen (PSA) among men at risk for prostate cancer." Cancer Causes & Control (2025): 1-8.

2. Yang, Yanxu, Yuan Wang, Hongke Wu, Nathaniel R. Geyer, Alicia C. McDonald, and Ming Wang. "Dietary Fiber Intake and Prostate Cancer Outcomes and All-Cause Mortality: Findings from a Secondary Analysis of the Prostate, Lung, Colorectal, and Ovarian (PLCO) Cancer Screening Study." Journal of the Academy of Nutrition and Dietetics (2025).

3. Alabbas, Mohammad, Yuqi Guo, Jingyi Catherine Shi, Hongke Wu, Shreya Sengupta, and Omar T. Sims. "Mo1652: FACTORS ASSOCIATED WITH ADVANCED FIBROSIS AMONG ADULTS WITH HEPATITIS C VIRUS IN THE UNITED STATES, 2007–2018." Gastroenterology 169, no. 1 (2025): S-1831.

4. Alabbas, Mohammad, Yuqi Guo, Jingyi Catherine Shi, Hongke Wu, Shreya Sengupta, and Omar T. Sims. "Sa1480: PREVALENCE OF AND FACTORS ASSOCIATED WITH CONCURRENT ALCOHOL USE AND ACTIVE SMOKING AMONG ADULTS LIVING WITH HCV IN THE UNITED STATES, 2007–2018: A POPULATION-LEVL ANALYSIS." Gastroenterology 169, no. 1 (2025): S-481.

5. Guo, Yuqi, Jingyi Catherine Shi, Mohammad Alabbas, Hongke Wu, Shreya Sengupta, and Omar T. Sims. "Sa1478: PREVALENCE AND CHARACTERISTICS OF EXCESSIVE ALCOHOL USE AMONG PEOPLE LIVING WITH HEPATITIS C IN THE UNITED STATES 2007–2018." Gastroenterology 169, no. 1 (2025): S-480.

6.  Wu, H., Weinstein, S., Moore, L.E. et al. Coffee intake and trace element blood concentrations in association with renal cell cancer among smokers. Cancer Causes Control (2021). <https://doi.org/10.1007/s10552-021-01505-2>

7.  Wu H, Wang M, Raman JD, McDonald AC. Association between urinary arsenic, blood cadmium, blood lead, and blood mercury levels and serum prostate-specific antigen in a population-based cohort of men in the United States. PLoS One. 2021 Apr 23;16(4):e0250744. doi: 10.1371/journal.pone.0250744. PMID: 33891655.

8. Pillai, Jagan, Hongke Wu, Wen Tang, Hao Feng, Chixiang Chen, James Leverenz, and Ming Wang. "Cognitive and Behavioral Subtypes of Alzheimer’s and Lewy Body Dementias with Distinct Clinical Characteristics (P3-9.003)." In Neurology, vol. 102, no. 17_supplement_1, p. 5199. Hagerstown, MD: Lippincott Williams & Wilkins, 2024.

9.  Hongke Wu, Melanie Potiaumpai, Shawna E. Doerksen, FACSM, Vernon M. Chinchilli, Li Wang, Rachel Lintz, Kathryn H. Schmitz, FACSM. Cost Evaluation of An Exercise Oncology Intervention: The ENACT Trial. Poster Presentation at the American College of Sports Medicine (ACSM) 2021 Annual Meeting. June 1-5, 2021; Virtual Meeting. #3715.

10.  Wu H, Wang M, McDonald AC. Association between levels of urinary caffeine and caffeine metabolite and elevated serum PSA among men at risk for prostate cancer. Oral Presentation at The American Public Health Association (APHA) 2020 Annual Meeting; Oct 27th, 2020; Virtual Meeting. Abstract #480015.

11.  Rebecca Volpe, PhD; Margaret Hopkins, MEd; Jasmine Geathers, GSII; Hongke Wu; Yendelela Cuffee, PhD. Investigating structural inequities in the culture of medicine. Paper Presentation at the 2020 American Society for Bioethics and Humanities (ASBH) Annual Conference; Oct 16th, 2020; Virtual Meeting.

12.  Wu H, Wang M, Raman JD, McDonald AC. Evaluation of serum prostate-specific antigen levels and levels of heavy metals (urinary arsenic and blood cadmium, lead, and mercury) among men at risk for prostate cancer. Oral presented at: The American Public Health Association (APHA) 2019 Annual Meeting; Nov 2nd, 2019; Philadelphia, PA. Abstract #445353.

13.  Dhruvil Shah, Kara A. Negrini, Katherine Wehrung, Abigail Haworth, Dan Lin, Hongke Wu, Sri-Rajasekhar Kothapalli, Alison Chetlan, Kathleen M. Sturgeon. Utilizing Photoacoustic Imaging to Detect Differences in Mammary Tumor Vasculature Between Exercise and Sedentary Rats. American College of Sports Medicine. Conference Abstract (2023 May)

14.  Brett Gordon, Hongke Wu, Stephen Baker, Matthew Herring, Kathryn Schmitz. The Effect of Physical Activity On Anxiety Symptoms In Cancer Survivors, A Systematic Review And Meta-analysis. American College of Sports Medicine. Conference Abstract (2023 May)

15.  McDonald AC, Gernand J, Geyer NR, Wu H, Yang Y, Wang M. Ambient air exposures to arsenic and cadmium and overall and prostate cancer-specific survival among prostate cancer cases in Pennsylvania, 2004 to 2014. Cancer. 2022;128(9):1832-1839. doi:10.1002/cncr.34128

16. Dougherty, E.C., Burse, N., Butzner, M., Wu H. et al. Examining medication adherence and preferences for a lifestyle intervention among Black and Latinx adults with hypertension: a feasibility study. Pilot Feasibility Stud 7, 209 (2021). <https://doi.org/10.1186/s40814-021-00930-z>

17. Potiaumpai M, Doerksen SE, Chinchilli VM, Wu H, Wang L, Lintz R, Schmitz KH. Cost evaluation of an exercise oncology intervention: The exercise in all chemotherapy trial. Cancer Rep (Hoboken). 2021 Jul 8:e1490. doi: 10.1002/cnr2.1490. Epub ahead of print. PMID: 34236137.

18. Guo, Y., Shi, C., Hongke,W., Alabbas, M., Sengupta, S., Sims, O.T. (in progress). Prevalence of Alcohol Use Among People Living with HCV in the United States: An 11-year Epidemiologic Trends Analysis.

19. Miller, Alaina1; Wu, Hongke2; Bowen, Kelly2; Aleyadeh, Wesam2; Flocco, Gianina2; Sims, Omar2; Lindenmeyer, Christina2; Kapoor, Aanchal3. 450: REASON FOR ADMISSION AS A PREDICTOR OF OUTCOMES IN A LIVER DISEASE-SPECIFIC INTENSIVE CARE UNIT. Critical Care Medicine 53(1):, January 2025. | DOI: 10.1097/01.ccm.0001100464.68512.bf 
